name: Bundle Deployment for house-price-prediction Prod
'on':
  push:
    branches:
    - release
  workflow_dispatch: null
defaults:
  run:
    working-directory: ./house_price_prediction
env:
  ARM_TENANT_ID: ${{ secrets.PROD_AZURE_SP_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.PROD_AZURE_SP_APPLICATION_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.PROD_AZURE_SP_CLIENT_SECRET }}
jobs:
  prod:
    concurrency: house-price-prediction-prod-bundle-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: databricks/setup-cli@main
    - name: Validate Bundle For Prod Environment
      id: validate
      run: 'databricks bundle validate -e prod

        '
    - name: Deploy Bundle to Prod Environment
      id: deploy
      run: 'databricks bundle deploy -e prod

        '
