name: Bundle Deployment for house-price-prediction Staging
'on':
  push:
    branches:
    - main
  workflow_dispatch: null
defaults:
  run:
    working-directory: ./house_price_prediction
env:
  ARM_TENANT_ID: ${{ secrets.STAGING_AZURE_SP_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.STAGING_AZURE_SP_APPLICATION_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.STAGING_AZURE_SP_CLIENT_SECRET }}
jobs:
  staging:
    concurrency: house-price-prediction-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: databricks/setup-cli@main
    - name: Validate Bundle For Staging Environment
      id: validate
      run: 'databricks bundle validate -e staging

        '
    - name: Deploy Bundle to Staging Environment
      id: deploy
      run: 'databricks bundle deploy -e staging

        '
